# Generated by Django 2.2 on 2019-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commenttable',
            fields=[
                ('commentid', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('storyid', models.IntegerField(db_column='storyID')),
                ('fragmentid', models.IntegerField(db_column='fragmentID')),
                ('content', models.TextField()),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('useremail', models.CharField(db_column='userEmail', max_length=50)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('likescount', models.IntegerField(blank=True, db_column='likesCount', null=True)),
            ],
            options={
                'db_table': 'commentTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fragmenttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('useremail', models.CharField(db_column='userEmail', max_length=50)),
                ('content', models.TextField()),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('commentscount', models.IntegerField(blank=True, db_column='commentsCount', null=True)),
                ('likescount', models.IntegerField(blank=True, db_column='likesCount', null=True)),
                ('storyid', models.IntegerField(db_column='storyID')),
                ('branchid', models.IntegerField(db_column='branchID')),
                ('branchleft', models.IntegerField(blank=True, db_column='branchLeft', null=True)),
                ('branchright', models.IntegerField(blank=True, db_column='branchRight', null=True)),
            ],
            options={
                'db_table': 'fragmentTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('useremail', models.CharField(db_column='userEmail', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('likescount', models.IntegerField(blank=True, db_column='likesCount', null=True)),
                ('fragmentcapacity', models.IntegerField(blank=True, db_column='fragmentCapacity', null=True)),
                ('fragmentscount', models.IntegerField(blank=True, db_column='fragmentsCount', null=True)),
                ('branch', models.CharField(blank=True, max_length=1, null=True)),
                ('wordslimit', models.CharField(blank=True, db_column='wordsLimit', max_length=1, null=True)),
                ('finished', models.CharField(blank=True, max_length=1, null=True)),
                ('modified', models.CharField(blank=True, max_length=1, null=True)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('beginning', models.IntegerField()),
            ],
            options={
                'db_table': 'storyTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('useremail', models.CharField(db_column='userEmail', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userTable',
                'managed': False,
            },
        ),
    ]
