# Generated by Django 2.2 on 2019-05-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenttable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fragmenttable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storytable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={},
        ),
    ]
