# Generated by Django 2.2 on 2019-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytable',
            name='ineditable',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
