# Generated by Django 2.2 on 2019-05-24 23:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('PuzzModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optype', models.CharField(max_length=20)),
                ('targetid', models.IntegerField()),
                ('fromuser', models.CharField(max_length=150)),
                ('fromnickname', models.CharField(max_length=20)),
                ('touser', models.CharField(max_length=150)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('sof', models.BooleanField()),
                ('storyid', models.IntegerField(blank=True, null=True)),
                ('fragid', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=150)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('likescount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyid', models.IntegerField()),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('likescount', models.IntegerField(default=0)),
                ('commentscount', models.IntegerField(default=0)),
                ('branchid', models.IntegerField(default=0)),
                ('branchleft', models.IntegerField(blank=True, null=True)),
                ('branchright', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffid', models.IntegerField()),
                ('ffcontent', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=20)),
                ('editor', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remains', models.IntegerField(default=0)),
                ('branch', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=True)),
                ('likescount', models.IntegerField(default=0)),
                ('commentscount', models.IntegerField(default=0)),
                ('fragscount', models.IntegerField(default=1)),
                ('fragscountlimit', models.IntegerField(default=-1)),
                ('fragwordslimit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('avator', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
