# Generated by Django 2.2 on 2019-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0002_announcement_comment_fragment_story_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='rules',
            field=models.CharField(blank=True, max_length=310, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
