# Generated by Django 2.2 on 2019-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0002_storytable_ineditable'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytable',
            name='fragmentwordslimit',
            field=models.IntegerField(db_column='fragmentWordsLimit', default=0),
        ),
    ]
