# Generated by Django 2.2 on 2019-05-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0002_auto_20190503_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
