# Generated by Django 2.2 on 2019-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0003_auto_20190624_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
