# Generated by Django 2.2 on 2019-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0003_auto_20190503_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
