# Generated by Django 2.2 on 2019-05-12 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0003_storytable_fragmentwordslimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttable',
            name='createtime',
            field=models.DateTimeField(db_column='createTime', default=django.utils.timezone.now),
        ),
    ]
