# Generated by Django 2.2 on 2019-05-12 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0004_auto_20190513_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmenttable',
            name='createtime',
            field=models.DateTimeField(db_column='createTime', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='branch',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='createtime',
            field=models.DateTimeField(db_column='createTime', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='finished',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='ineditable',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='modified',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='storytable',
            name='wordslimit',
            field=models.CharField(blank=True, db_column='wordsLimit', default='0', max_length=1, null=True),
        ),
    ]
