# Generated by Django 2.2 on 2019-05-15 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0006_auto_20190515_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField()),
                ('headcontent', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('likescount', models.IntegerField(default=0)),
                ('commentscount', models.IntegerField(default=0)),
                ('fragscount', models.IntegerField(default=1)),
                ('fragscountlimit', models.IntegerField(default=-1)),
                ('fragwordslimit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='Storytable',
        ),
    ]
