# Generated by Django 2.2 on 2019-05-15 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0007_auto_20190515_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyid', models.IntegerField()),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('likescount', models.IntegerField(default=0)),
                ('commentscount', models.IntegerField(default=0)),
                ('branchid', models.IntegerField(default=0)),
                ('branchleft', models.IntegerField(blank=True, null=True)),
                ('branchright', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fragmenttable',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='headcontent',
            new_name='ffcontent',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='head',
            new_name='ffid',
        ),
    ]
