# Generated by Django 2.2 on 2019-05-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuzzModel', '0009_auto_20190515_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='modified',
            field=models.BooleanField(default=True),
        ),
    ]
